repos:
-   repo: local
    hooks:
    -   id: autoflake
        name: Run Autoflake
        entry: autoflake
        args: ["--remove-all-unused-imports", "--ignore-init-module-imports", "--remove-unused-variables","--in-place"]
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: isort
        name: Run Isort
        entry: isort
        args: ["--profile", "black", "--filter-files"]
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: black
        name: Run Black
        entry: black
        language: system
        types: [python]
